# Generated by Django 2.2.12 on 2020-05-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticulo', models.CharField(max_length=200)),
                ('caracteristica', models.CharField(max_length=200)),
                ('clasificacion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='proov_telas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProov', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTemporada', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('año', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTela', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('proovedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.proov_telas')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloUsaTela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso', models.CharField(max_length=100)),
                ('articuloID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Articulo')),
                ('tela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Tela')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='temporadas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Temporadas'),
        ),
        migrations.CreateModel(
            name='ArtEnTemporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Articulo')),
                ('temporada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Temporadas')),
            ],
        ),
    ]
